namespace Gibbed.RED.FileFormats.Script
{
    public enum OperatorCode
    {
        OperatorIntAdd = 0,
        OperatorIntSubtract = 1,
        OperatorIntMultiply = 2,
        OperatorIntDivide = 3,
        OperatorIntNeg = 4,
        OperatorIntEqual = 8,
        OperatorIntNotEqual = 9,
        OperatorIntLess = 10,
        OperatorIntLessEqual = 11,
        OperatorIntGreater = 12,
        OperatorIntGreaterEqual = 13,
        OperatorIntAssignAdd = 14,
        OperatorIntAssignSubtract = 15,
        OperatorStringAdd = 20,
        OperatorFloatAdd = 21,
        OperatorFloatSubtract = 22,
        OperatorFloatMultiply = 23,
        OperatorFloatDivide = 24,
        OperatorFloatEqual = 27,
        OperatorFloatNotEqual = 28,
        OperatorFloatLess = 29,
        OperatorFloatLessEqual = 30,
        OperatorFloatGreater = 31,
        OperatorFloatGreaterEqual = 32,
        OperatorFloatAssignAdd = 33,
        OperatorFloatAssignSubtract = 34,
        OperatorBoolAnd = 57,
        OperatorBoolOr = 58,
        OperatorBoolNot = 59,
    }
}