namespace Gibbed.RED.FileFormats.Script
{
    public enum OperatorCode
    {
        IntAdd = 0,
        IntSubtract = 1,
        IntMultiply = 2,
        IntDivide = 3,
        IntNeg = 4,
        IntEqual = 8,
        IntNotEqual = 9,
        IntLess = 10,
        IntLessEqual = 11,
        IntGreater = 12,
        IntGreaterEqual = 13,
        IntAssignAdd = 14,
        IntAssignSubtract = 15,
        StringAdd = 20,
        FloatAdd = 21,
        FloatSubtract = 22,
        FloatMultiply = 23,
        FloatDivide = 24,
        FloatOp25 = 25,
        FloatNeg = 26,
        FloatEqual = 27,
        FloatNotEqual = 28,
        FloatLess = 29,
        FloatLessEqual = 30,
        FloatGreater = 31,
        FloatGreaterEqual = 32,
        FloatAssignAdd = 33,
        FloatAssignSubtract = 34,
        FloatAssignMultiply = 35,
        BoolAnd = 57,
        BoolOr = 58,
        BoolNot = 59,
        VectorOp60 = 60,
        VectorOp62 = 62,
        VectorOp71 = 71,
        TimeOp80 = 80,
        TimeOp81 = 81,
        TimeOp94 = 94,
        TimeOp96 = 96
    }
}