namespace Gibbed.RED.FileFormats.Script
{
    public enum OperatorCode
    {
        IntAdd = 0,
        IntSubtract = 1,
        IntMultiply = 2,
        IntDivide = 3,
        OperatorIntNeg = 4,
        OperatorIntEqual = 8,
        OperatorIntNotEqual = 9,
        OperatorIntLess = 10,
        OperatorIntLessEqual = 11,
        OperatorIntGreater = 12,
        OperatorIntGreaterEqual = 13,
        IntAssignAdd = 14,
        IntAssignSubtract = 15,
        StringAdd = 20,
        FloatAdd = 21,
        FloatSubtract = 22,
        FloatMultiply = 23,
        FloatDivide = 24,
        OperatorFloatEqual = 27,
        OperatorFloatNotEqual = 28,
        OperatorFloatLess = 29,
        OperatorFloatLessEqual = 30,
        OperatorFloatGreater = 31,
        OperatorFloatGreaterEqual = 32,
        FloatAssignAdd = 33,
        FloatAssignSubtract = 34,
        OperatorBoolAnd = 57,
        OperatorBoolOr = 58,
        OperatorBoolNot = 59,
    }
}